name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега v*

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/onlinesimru
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build --wheel --sdist
    
    - name: Publish to PyPI
      # Для настройки Trusted Publisher:
      # 1. Перейдите по ссылке из предупреждения в логах
      # 2. Войдите в PyPI как владелец пакета
      # 3. Подтвердите настройку Trusted Publisher
      # 4. Используйте среду 'release' (не 'pypi')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
